windowrule {
    name = jarvis-overlay-float
    match:class = jarvis-overlay
    float = true
}

windowrule {
    name = jarvis-overlay-pin
    match:class = jarvis-overlay
    pin = true
}

windowrule {
    name = jarvis-overlay-noborder
    match:class = jarvis-overlay
    border_size = 0
}

windowrule {
    name = jarvis-overlay-nofocus
    match:class = jarvis-overlay
    suppress_event = focus
}

windowrule {
    name = jarvis-overlay-position
    match:class = jarvis-overlay
    move = 100%-268 100%-266
}

windowrule {
    name = jarvis-overlay-size
    match:class = jarvis-overlay
    size = 240 238
}
